### ISSUE TITLE
npm run dev only works when executed using root

### ISSUE THREAD

**Issue by adosaiguas** [inadarei/nodebootstrap#47]
I am on Ubuntu 14.04.3 LTS.

$ npm -v
2.13.1
$ nodejs -v
v0.12.9

But I get the following error:
```
$ npm run dev
> nodebootstrap-based-app@ dev <my project path>
> npm install supervisor -g && ./bin/dev_start.sh

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "supervisor" "-g"
npm ERR! node v0.12.9
npm ERR! npm  v2.13.1
npm ERR! path /usr/bin/node-supervisor
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/bin/node-supervisor'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/bin/node-supervisor'] errno: -13, code: 'EACCES', path: '/usr/bin/node-supervisor' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/node-supervisor'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/node-supervisor'] errno: -13, code: 'EACCES', path: '/usr/bin/node-supervisor' }

npm ERR! Please include the following file with any support request:
npm ERR!     <my project path>/npm-debug.log

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.9
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE
npm ERR! nodebootstrap-based-app@ dev: `npm install supervisor -g && ./bin/dev_start.sh`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the nodebootstrap-based-app@ dev script 'npm install supervisor -g && ./bin/dev_start.sh'.
npm ERR! This is most likely a problem with the nodebootstrap-based-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install supervisor -g && ./bin/dev_start.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodebootstrap-based-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     <my project path>/npm-debug.log
```

Of course, I already installed supervisor using this command:
```
sudo npm install supervisor -g
```

Oh, and btw, it runs without problems when I run it with sudo:

```
$ sudo npm run dev

> nodebootstrap-based-app@ dev <my project path>
> npm install supervisor -g && ./bin/dev_start.sh

/usr/bin/node-supervisor -> /usr/lib/node_modules/supervisor/lib/cli-wrapper.js
/usr/bin/supervisor -> /usr/lib/node_modules/supervisor/lib/cli-wrapper.js
supervisor@0.9.1 /usr/lib/node_modules/supervisor

Running node-supervisor with
  program '<my project path>/server.js'
  --watch './lib,<my project path>/config,<my project path>/server.js'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node <my project path>/server.js'
Watching directory '<my project path>/lib' for changes.
Press rs for restarting the process.
Watching directory '<my project path>/config' for changes.
Press rs for restarting the process.
Watching directory '<my project path>/server.js' for changes.
Press rs for restarting the process.
7 Dec 16:57:35 - NOTICE  [node_modules/nodebootstrap-server/app.js:35] Express server instance listening on port 3000
```

**Comment by inadarei** [comment]
So,

the problem you are running into is that:

1. `npm run dev` tries to install supervisor, just in case it is not already installed (not a bad thing to do, in general)
2. When "supervisor" is already installed, it looks like NPM is trying to uninstall it and re-install it, instead of just skipping. Not sure why, that's a question to NPM project.
3. The way you have Node set up, it looks like you need root privileges to install something globally.

There are couple things you can do:

1. Address #3, if you can
2. Nodebootstrap creates a skeleton of a project. You can (and in most cases will) modify it further to mold it to your needs. Sounds like you don't care for package.json to be verifying installation of supervisor because you know you have it. Edit package.json and remove that piece from the dev script. You may also, similarly, want to remove the installation of "forever" from the start script. That should fix the problem for you.

cheers,

Irakli

**Comment by inadarei** [comment]
To be clear, this is what your package.json's corresponding part should like like, after the modifications:

```
  "scripts": {
    "start": "./bin/start.sh",
    "dev": "./bin/dev_start.sh",
```

**Comment by adosaiguas** [comment]
Yes, that did the trick.
I did not notice the command was setup in the packages.json file.
Btw, all Linux OSs will require root privileges in order to install a module globally... Maybe you should warn your users about this issue?

**Comment by inadarei** [comment]
Yes, I will add a warning to the documentation but "all Linux OSs will require root privileges in order to install a module globally" is not quite accurate. You can:

1. Install Node via [NVM](https://github.com/creationix/nvm) in which case you will not be running into the issues you experienced. NVM is a very common way of setting up development environment for Node.
2. Install Node via Docker. With most Docker/Node images you again won't be running into this issue.
3. You could also set up your Node so that modules are not going under /usr/bin but are installed under /usr/local/bin or some other location where you don't need root privileges for writing files.

so there are definitely options here, but adding a warning to the docs is still a good idea.

Thanks

**Comment by adosaiguas** [comment]
Thanks for ponting out the other options. I'll take a look at them.
