### ISSUE TITLE
Add option for es6 coding style

### ISSUE THREAD

**Issue by jhnlsn** [inadarei/nodebootstrap#93]
Add new functionality to support es6 functionality.  Maybe as an option flag when creating a new project.

**Comment by inadarei** [comment]
Yeah, actually @justinbach is preparing a big PR on that. Moving to JSLint and modernizing style checks significantly... Hopefully soon :)

**Comment by inadarei** [comment]
I am moving to Node 6.x in nodebootstrap-microservices, as the default and only option. Some thoughts:

1. The microservice version is intended to run in Docker, where getting Node 6.x + shouldn't be a problem
2. Since 8.x is stable now, we can consider bet on 6.x a safe bet
3. Nodebootstrap is for bootstrapping new projects so backwards-compatibility should be a small consideration (maybe only: backwards compatibility to older environments, but again - running in a container should mitigate that for nodebootstrap-microservice)

**Comment by inadarei** [comment]
Done https://github.com/inadarei/nodebootstrap-microservice/blob/master/.eslintrc.yml
